version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Build Docker
          command: |
            docker build -t ntubapp/ntub-app-server:$CIRCLE_BRANCH .
            docker tag ntubapp/ntub-app-server:$CIRCLE_BRANCH ntubapp/ntub-app-server:$CIRCLE_SHA1

      - run:
          name: Push to Docker Hub
          command: |
            docker push ntubapp/ntub-app-server:$CIRCLE_BRANCH
            docker push ntubapp/ntub-app-server:$CIRCLE_SHA1

    deploy:
      machine: true
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - "4b:7a:f5:16:54:4a:18:5a:85:e8:1d:41:48:82:79:58"

        - run:
            name: Copy docker-compose to server
            command: |
              scp -P $PORT deploy/docker-compose.yml $USER@$HOST:$PROJECT_ROOT
              ssh -p $PORT $USER@$HOST << EOF
              ls
              pwd
              whoami
              EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

      - deploy:
          requires:
            - build

          filters:
            branches:
              only:
                - master
